Fix k8s postgres quote passthrough
runwhen-contrib/rw-public-codecollection pull request #92
Opened 2023-03-14 16:54 UTC by jon-funk

2023-03-14 16:58 UTC, jon-funk commented
Having the query in the /tmp file was super helpful for troubleshooting btw - let me quickly identify how the query was getting parsed and sent in.

2023-03-14 17:10 UTC, jon-funk commented
`"` are getting dropped at the tail end of the passthrough, investigating..

2023-03-14 19:09 UTC, jon-funk commented
Tested for both the runbook and sli. Let me know if you hit any issues.

2023-03-15 14:39 UTC, stewartshea commented
I just tried a single quote around the string: 

- From the CLI
```
# SELECT pid,now() - pg_stat_activity.query_start AS duration,query,state FROM pg_stat_activity WHERE (now() - pg_stat_activity.query_start) > interval '5 minutes' AND state = 'active';
 pid |        duration        |                   query                    | state  
-----+------------------------+--------------------------------------------+--------
 402 | 2 days 01:29:58.224487 | START_REPLICATION 1A7/46000000 TIMELINE 14 | active

```

robot ouput shows the command as: 
```
SELECT pid,now() - pg_stat_activity.query_start AS duration,query,state FROM pg_stat_activity WHERE (now() - pg_stat_activity.query_start) > interval 5 minutes AND state = active;
```

Double quotes don't work with this query, and if attempted, fails.

2023-03-15 14:42 UTC, stewartshea commented
Btw, this is related to internal issue https://github.com/runwhen/platform-core/issues/739 for ref.

2023-03-15 14:44 UTC, stewartshea requested changes

2023-03-15 14:44 UTC, stewartshea commented on libraries/RW/Postgres/postgres.py
> +        query = query.replace('"', '\\\\\\"')
the problem is with single quotes; maybe doubles are also an issue, but related to the queries we were attempting, we need single quotes escaped.

2023-03-15 15:07 UTC, stewartshea commented
I was testing this on the wrong codebundle. so at first was chasing down a double/single quote issue but this seems to work in the codebundles you have edited here. I'm going to add in the database triage to see if it works too.

2023-03-15 15:15 UTC, jon-funk commented
ack - thought I was losing my mind lol - let me know if you hit anything there after making the changes

2023-03-15 15:16 UTC, stewartshea commented
Hah, I thought I was losing my mind too! 

This looks like it works just fine! Nice work on this! 
![image](https://user-images.githubusercontent.com/18314168/225355307-110b5576-dda7-499b-baec-3746a220402e.png)

2023-03-15 15:16 UTC, merged